PRODUCTS = [
    {
        "product_id": 90,
        "category_id": 14,
        "producer_id": 6,
        "product_name": "Portfel męski N992-WA1 BROWN",
        "product_name_additional": "brązowy skórzany portfel męski Always Wild",
        "price": "50.0",
        "visible": 1,
        "keywords": "Portfel męski N992 WA1a N992WA1 BROWN brązowy skórzany portfel Always Wild meski brazowy skorzany",
        "zestaw": 0,
    },
    {
        "product_id": 464,
        "category_id": 39,
        "producer_id": 1,
        "product_name": "PASEK PARCIANY K1-SN-P1",
        "product_name_additional": "pasek parciany z klamrą w kolorze niklu",
        "price": "19.9",
        "visible": 1,
        "keywords": "PASEK PARCIANY K1aa SNaa P1aa K1SNP1 pasek parciany klamrą kolorze niklu Zagatto klamra",
        "zestaw": 0,
    },
    {
        "product_id": 24,
        "category_id": 62,
        "producer_id": 1,
        "product_name": "Portfel damski na bigiel Zagatto ZG-100-SC RFID RED",
        "product_name_additional": "skórzany portfel damski Zagatto",
        "price": "100.0",
        "visible": 1,
        "keywords": "Portfel damski naaa bigiel Zagatto ZGaa 100a SCaa ZG100SC RFID REDa skórzany portfel 5907518361102 skorzany",
        "zestaw": 0,
    },
]
VARIANTS = [
    {
        "produkty_wariant_id": 646,
        "produkt_id": 464,
        "pozycja": 1,
        "ilosc": "0.0",
        "wariant_cena": "19.9",
        "wariant_cena1": "59.0",
        "wariant_cena2": None,
        "wariant_cena3": None,
        "zdjecie_nr": 0,
        "stawka_vat": 23,
        "domyslny": 1,
        "kod_produktu": "K1-SN-P1-S",
        "wariant_cena_aukcji": None,
        "termin_dostawy": "",
    },
    {
        "produkty_wariant_id": 647,
        "produkt_id": 464,
        "pozycja": 2,
        "ilosc": "0.0",
        "wariant_cena": "19.9",
        "wariant_cena1": "59.0",
        "wariant_cena2": None,
        "wariant_cena3": None,
        "zdjecie_nr": 0,
        "stawka_vat": 23,
        "domyslny": 0,
        "kod_produktu": "K1-SN-P1-M",
        "wariant_cena_aukcji": None,
        "termin_dostawy": "",
    },
    {
        "produkty_wariant_id": 648,
        "produkt_id": 464,
        "pozycja": 3,
        "ilosc": "0.0",
        "wariant_cena": "19.9",
        "wariant_cena1": "59.0",
        "wariant_cena2": None,
        "wariant_cena3": None,
        "zdjecie_nr": 0,
        "stawka_vat": 23,
        "domyslny": 0,
        "kod_produktu": "K1-SN-P1-L",
        "wariant_cena_aukcji": None,
        "termin_dostawy": "",
    },
    {
        "produkty_wariant_id": 649,
        "produkt_id": 464,
        "pozycja": 4,
        "ilosc": "67.0",
        "wariant_cena": "19.9",
        "wariant_cena1": "59.0",
        "wariant_cena2": None,
        "wariant_cena3": None,
        "zdjecie_nr": 0,
        "stawka_vat": 23,
        "domyslny": 0,
        "kod_produktu": "K1-SN-P1-XL",
        "wariant_cena_aukcji": None,
        "termin_dostawy": "",
    },
    {
        "produkty_wariant_id": 2307,
        "produkt_id": 24,
        "pozycja": 1,
        "ilosc": "109.0",
        "wariant_cena": "100.0",
        "wariant_cena1": "300.0",
        "wariant_cena2": None,
        "wariant_cena3": None,
        "zdjecie_nr": 30,
        "stawka_vat": 23,
        "domyslny": 1,
        "kod_produktu": "ZG-100-SC RED",
        "wariant_cena_aukcji": None,
        "termin_dostawy": "",
    },
]
VARIANTS_ATTRIBUTES = [
    {"produkty_wariant_id": 646, "produkty_atrybut_id": 137},
    {"produkty_wariant_id": 647, "produkty_atrybut_id": 138},
    {"produkty_wariant_id": 648, "produkty_atrybut_id": 139},
    {"produkty_wariant_id": 649, "produkty_atrybut_id": 140},
    {"produkty_wariant_id": 2307, "produkty_atrybut_id": 6},
]
ATTRIBUTES = [
    {"produkty_atrybut_id": 137, "produkty_atrybuty_grupa_id": 12, "pozycja": 2, "produkty_atrybut": "S - 105 cm"},
    {"produkty_atrybut_id": 138, "produkty_atrybuty_grupa_id": 12, "pozycja": 3, "produkty_atrybut": "M - 115 cm"},
    {"produkty_atrybut_id": 139, "produkty_atrybuty_grupa_id": 12, "pozycja": 4, "produkty_atrybut": "L - 120 cm"},
    {"produkty_atrybut_id": 140, "produkty_atrybuty_grupa_id": 12, "pozycja": 5, "produkty_atrybut": "XL - 135 cm"},
    {"produkty_atrybut_id": 6, "produkty_atrybuty_grupa_id": 1, "pozycja": 1, "produkty_atrybut": "czerwony"},
]
ATTRIBUTES_GROUPS = [
    {
        "produkty_atrybuty_grupa_id": 12,
        "pozycja": 12,
        "produkty_atrybuty_grupa": "Długość paska",
        "sposob_wyswietlania_atrybutow": "select",
    },
    {
        "produkty_atrybuty_grupa_id": 1,
        "pozycja": 1,
        "produkty_atrybuty_grupa": "Kolor",
        "sposob_wyswietlania_atrybutow": "radio",
    },
]
DETAILS = [
    {
        "produkt_id": 90,
        "kod_producenta": "N992-WA1 BROWN",
        "kod_dostawcy": None,
        "cena_poprzednia": "100.0",
        "stawka_vat": 23,
        "html_title": "Portfel skórzany męski always wild n992 wa1 d.Brwon | Zagatto",
        "html_description": "Portfel skórzany męski marki Always Wild N992 WA1 w kolorze brązowym. Wykonany z wytrzymałej, grubej skóry nubukowej, z wszelkimi niezbędnymi przegrodami. W komplecie pudełko firmowe. Dwa lata gwarancji.",
        "html_keywords": "",
        "tekst_promocyjny": "-15% i darmowa dostawa z kodem ZAKUPYZDOMU",
        "opis": '<p style="margin-bottom: 0cm;" align="JUSTIFY"><span style="color: #000080;"><span style="color: #000000;"><span style="text-decoration: none;"><strong>Piękno i wytrzymałość – skóra nubukowa </strong></span></span></span></p>\r\n<p>Portfel męski Always Wild wykonany ze skóry nubukowej, która charakteryzuje się niejednorodną strukturą. Ma krótkie włosie dodatkowo zabezpieczone, dzięki czemu lepiej znosi długotrwałe użytkowanie. Skóra od zawsze jest symbolem wysokiej jakości, która pożądana jest zarówno przez kobiety, jak również przez mężczyzn.</p>\r\n<p style="margin-bottom: 0cm;" align="JUSTIFY"><span style="color: #000080;"><span style="color: #000000;"><span style="text-decoration: none;"><strong>Portfel skórzany </strong></span></span></span><span style="color: #000080;"><span style="color: #000000;"><span style="text-decoration: none;">to nie tylko ponadczasowy styl i sprawdzony dodatek. Dbamy o to, aby był on też praktyczny i pozwolił na noszenie nie tylko kart i dokumentów, ale także zdjęcia bliskich. <br /></span></span></span></p>\r\n<p style="margin-bottom: 0cm;" align="JUSTIFY"><span style="color: #000080;"><span style="color: #000000;"><span style="text-decoration: none;"><strong>Kto nie lubi prezentów?</strong></span></span></span></p>\r\n<p style="margin-bottom: 0cm;" align="JUSTIFY"><span style="color: #000080;"><span style="color: #000000;"><span style="text-decoration: none;"><strong>Portfel męski ze skóry </strong></span></span></span><span style="color: #000080;"><span style="color: #000000;"><span style="text-decoration: none;">to idealny prezent dla męża, narzeczonego, przyjaciela, syna lub taty. W zestawie znajdą Państwo eleganckie pudełko, które można wykorzystać jako opakowanie prezentu.</span></span></span></p>\r\n<p style="margin-bottom: 0cm;" align="JUSTIFY">\xa0</p>\r\n<table border="1">\r\n<tbody>\r\n<tr>\r\n<td>\r\n<p><span class="_5yl5"><strong>Wysokość:</strong></span></p>\r\n</td>\r\n<td><span class="_5yl5">9,5 cm</span></td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<p><span class="_5yl5"><strong>Szerokość:</strong> </span></p>\r\n</td>\r\n<td><span class="_5yl5">13 cm</span></td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<p><span class="_5yl5"><strong>Grubość:</strong></span></p>\r\n</td>\r\n<td><span class="_5yl5">3,5 cm</span></td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<p><span class="_5yl5"><strong>Materiał:</strong></span></p>\r\n</td>\r\n<td><span class="_5yl5">skóra naturalna</span></td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<p><span class="_5yl5"><strong>Zapięcie:</strong> <br /></span></p>\r\n</td>\r\n<td><span class="_5yl5">zatrzask<br /></span></td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<p><strong><span class="_5yl5">Przegrody:</span></strong></p>\r\n</td>\r\n<td>\r\n<ul>\r\n<li><span class="_5yl5"><span class="_5yl5"><span class="_5yl5"><span>6x kieszeń na karty</span></span></span></span></li>\r\n<li><span class="_5yl5"><span class="_5yl5"><span><span class="_5yl5"><span><span class="_5yl5"><span><span class="_5yl5"><span>2x kieszeń na banknoty</span></span></span></span></span></span></span></span></span></li>\r\n<li><span class="_5yl5"><span class="_5yl5"><span class="_5yl5"><span>1x <span class="_5yl5"><span>kieszeń na bilon (zamykana na zatrzask)</span></span></span></span></span></span></li>\r\n<li><span class="_5yl5"><span class="_5yl5"><span><span class="_5yl5"><span><span class="_5yl5"><span>1x schowek na dokumenty zamykany na suwak</span></span></span></span></span></span></span></li>\r\n<li><span class="_5yl5"><span class="_5yl5"><span class="_5yl5"><span><span class="_5yl5"><span><span class="_5yl5"><span>3x schowek na dokumenty </span></span></span></span></span></span></span></span></li>\r\n<li><span class="_5yl5">3x <span class="_5yl5"><span>kieszeń z okienkiem</span></span></span><br /><span class="_5yl5"><span class="_5yl5"><span></span></span></span></li>\r\n</ul>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<p><strong><span class="_5yl5">Inne:</span></strong></p>\r\n</td>\r\n<td>firmowe pudełko</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>\xa0</p>',
        "opis_skrocony": "",
        "zdjecie_nr": 8,
        "zdjecia_katalog": "img/products/90/",
        "promocja": None,
        "promocja_kategorii": 0,
        "dostawa": "",
        "produkt_htaccess": "portfel-always-wild-n992-wa1-d-brown",
        "magazyn_id": 1,
        "liczba_egzemplarzy": "6.0",
        "waga": 0.0,
        "gabaryt": 0,
        "opis_filmy": "",
        "symbol_produktu": "N992-WA1 BROWN",
        "rabat_grupa_id": 0,
        "cena_poziom1": None,
        "cena_poziom2": None,
        "cena_poziom3": None,
        "ilosc_dokladnosc": 0,
        "ilosc_min": "1.0",
        "ilosc_przyrost": "1.0",
        "kod_ean": "",
        "dostepnosc": "",
        "aukcja_zdjecie": "",
        "cena_aukcji": None,
        "opis_aukcji": None,
        "porownywarki_reklama": "",
    },
    {
        "produkt_id": 464,
        "kod_producenta": "K1-SN-P1",
        "kod_dostawcy": None,
        "cena_poprzednia": "59.0",
        "stawka_vat": 23,
        "html_title": "Pasek parciany zagatto k1-sn p1",
        "html_description": "Pasek męski parciany marki Zagatto. Niklowana metalowa klamra.",
        "html_keywords": "",
        "tekst_promocyjny": "-15% i darmowa dostawa z kodem ZAKUPYZDOMU",
        "opis": "<p><strong>Pasek parciany marki Zagatto. Z hologramem autentyczności Zagatto®. <br /></strong></p>\r\n<p><strong>Bardzo wytrzymały.<br /></strong></p>\r\n<p><strong>5 lat gwarancji!</strong></p>\r\n<p><strong>\xa0</strong></p>",
        "opis_skrocony": "",
        "zdjecie_nr": 3,
        "zdjecia_katalog": "img/products/46/4/",
        "promocja": "hit,glowna",
        "promocja_kategorii": 1,
        "dostawa": "24h",
        "produkt_htaccess": "pasek-parciany-zagatto-k1-sn-p1",
        "magazyn_id": 1,
        "liczba_egzemplarzy": None,
        "waga": None,
        "gabaryt": 0,
        "opis_filmy": "",
        "symbol_produktu": "K1-SN-P1",
        "rabat_grupa_id": 0,
        "cena_poziom1": None,
        "cena_poziom2": None,
        "cena_poziom3": None,
        "ilosc_dokladnosc": 0,
        "ilosc_min": "1.0",
        "ilosc_przyrost": "1.0",
        "kod_ean": "",
        "dostepnosc": "",
        "aukcja_zdjecie": "",
        "cena_aukcji": None,
        "opis_aukcji": None,
        "porownywarki_reklama": "",
    },
    {
        "produkt_id": 24,
        "kod_producenta": "ZG-100-SC RED",
        "kod_dostawcy": None,
        "cena_poprzednia": "300.0",
        "stawka_vat": 23,
        "html_title": "Portfel skórzany damski ZG-100-SC RED RFID | Zagatto",
        "html_description": "Portfel skórzany damski Zagatto ZG-100-SC RED RFID",
        "html_keywords": "",
        "tekst_promocyjny": "-15% i darmowa dostawa z kodem ZAKUPYZDOMU",
        "opis": '<p><strong>Piękno i jakość, na które zasługujesz </strong></p>\r\n<p style="margin-bottom: 0cm; text-align: justify;">Portfel jest jednym z atrybutów kobiety. Zazwyczaj dopasowujemy go pod względem kolorystyki i wzoru do torebki i całej stylizacji. Powinien być zatem uniwersalny, a jednocześnie odzwierciedlać nasz charakter. <strong>Portfel damski skórzany </strong>Zagatto z kolekcji Savona to klasyka ubrana we współczesne piękno. Stworzony został z wykorzystaniem naturalnej skóry – trwałej, wytrzymałej i prezentującej sobą najwyższą jakość. Jest odporny na blaknięcie koloru, przetarcia i inne uszkodzenia. To produkt, który doskonale sprawdza się niezależnie od warunków, portfel będący symbolem współczesnego piękna na najwyższym poziomie.</p>\r\n<p><strong>Czerwony – optymizm i brak ograniczeń </strong></p>\r\n<p>Portfel może być w różnym kolorze, jednak to ten w kolorze czerwonym według opinii wielu kobiet zapewnia stabilność finansową. <strong>Portfel ze skóry </strong>idealnie pasuje do osób przepełnionych radością i optymizmem. Czerwień jest symbolem odwagi oraz temperamentu, a więc będzie doskonałą propozycją dla kobiety współczesnej.</p>\r\n<p><strong>Praktyczny – nie tylko na specjalne okazje </strong></p>\r\n<p>Wyposażono go w dużą ilość przegródek, ponieważ wiemy, że w żadnym portfelu nie może zabraknąć miejsca na karty, dokumenty i pieniądze. Masz do dyspozycji: 4 kieszenie na karty, cztery kieszenie na dokumenty, kieszeń na zdjęcie, schowek na dokumenty, kieszeń na bilon i 2 kieszenie na banknoty.</p>\r\n<p><strong>Bezpieczny – cenimy sobie Twoją satysfakcję </strong></p>\r\n<p>Wszystkie <strong>portfele Zagatto </strong>posiadają skuteczne zabezpieczenie RFID. Większość kart obecnie posiada funkcję płatności zbliżeniowych, co ułatwia złodziejom pozyskanie danych i środków pieniężnych. Taka ochrona gwarantuje pewność, że karty są chronione przed skanowaniem.</p>\r\n<p><strong>Skórzany – elegancja i styl </strong></p>\r\n<p>Naturalna skóra to wysoka jakość i niepowtarzalna elegancja. <strong>Portfel skórzany </strong>jest więc tym, który spełni oczekiwania najbardziej wymagających kobiet.</p>',
        "opis_skrocony": "",
        "zdjecie_nr": 32,
        "zdjecia_katalog": "img/products/24/",
        "promocja": None,
        "promocja_kategorii": 0,
        "dostawa": "WYSYŁKA<span>W 24H</span>",
        "produkt_htaccess": "portfel-skorzany-damski-zagatto500-sc-red",
        "magazyn_id": 1,
        "liczba_egzemplarzy": None,
        "waga": 0.0,
        "gabaryt": 0,
        "opis_filmy": "",
        "symbol_produktu": "ZG-100-SC RED",
        "rabat_grupa_id": 0,
        "cena_poziom1": None,
        "cena_poziom2": None,
        "cena_poziom3": None,
        "ilosc_dokladnosc": 0,
        "ilosc_min": "1.0",
        "ilosc_przyrost": "1.0",
        "kod_ean": "5907518361102",
        "dostepnosc": "",
        "aukcja_zdjecie": "0",
        "cena_aukcji": None,
        "opis_aukcji": None,
        "porownywarki_reklama": "",
    },
]
IMAGES = [
    {"produkt_id": 90, "zdjecie_nr": 10, "zdjecie_pozycja": 2, "zdjecie_opis": "N992 WA1 D.BROWN - kieszeń na zdjęcie"},
    {
        "produkt_id": 90,
        "zdjecie_nr": 11,
        "zdjecie_pozycja": 3,
        "zdjecie_opis": "N992 WA1 D.BROWN - kieszenie z okienkiem",
    },
    {"produkt_id": 90, "zdjecie_nr": 7, "zdjecie_pozycja": 7, "zdjecie_opis": "N992 WA1 D.BROWN - kieszeń na bilon"},
    {
        "produkt_id": 90,
        "zdjecie_nr": 6,
        "zdjecie_pozycja": 6,
        "zdjecie_opis": "N992 WA1 D.BROWN - wewnętrzna kieszeń na zamek",
    },
    {
        "produkt_id": 90,
        "zdjecie_nr": 5,
        "zdjecie_pozycja": 9,
        "zdjecie_opis": "N992 WA1 D.BROWN - sześć kieszeni na karty",
    },
    {
        "produkt_id": 90,
        "zdjecie_nr": 4,
        "zdjecie_pozycja": 8,
        "zdjecie_opis": "N992 WA1 D.BROWN - dwie kieszenie z okienkiem",
    },
    {"produkt_id": 90, "zdjecie_nr": 3, "zdjecie_pozycja": 10, "zdjecie_opis": "N992 WA1 D.BROWN - widok wewnątrz"},
    {"produkt_id": 90, "zdjecie_nr": 2, "zdjecie_pozycja": 11, "zdjecie_opis": "N992 WA1 D.BROWN - widok z frontu"},
    {"produkt_id": 90, "zdjecie_nr": 8, "zdjecie_pozycja": 0, "zdjecie_opis": "N992 WA1 D.BROWN - przód portfela"},
    {"produkt_id": 90, "zdjecie_nr": 12, "zdjecie_pozycja": 4, "zdjecie_opis": "N992 WA1 D.BROWN - kieszenie na karty"},
    {"produkt_id": 90, "zdjecie_nr": 9, "zdjecie_pozycja": 5, "zdjecie_opis": "N992 WA1 D.BROWN - tył portfela"},
    {"produkt_id": 464, "zdjecie_nr": 2, "zdjecie_pozycja": 3, "zdjecie_opis": "K1-SN-P1 tył paska"},
    {"produkt_id": 464, "zdjecie_nr": 1, "zdjecie_pozycja": 2, "zdjecie_opis": "K1-SN-P1 przód paska"},
    {"produkt_id": 464, "zdjecie_nr": 4, "zdjecie_pozycja": 4, "zdjecie_opis": "K1-SN-P1 pudełko"},
    {"produkt_id": 464, "zdjecie_nr": 3, "zdjecie_pozycja": 0, "zdjecie_opis": "K1-SN-P1 miniaturka"},
    {"produkt_id": 24, "zdjecie_nr": 30, "zdjecie_pozycja": 30, "zdjecie_opis": ""},
]
COIN = {"coin": 2137}
TOKEN = {"success": {"token": "c0acbe5d0cdda577b1bf21379cdad6a5", "expire_at": "2020-04-21T09:51:32.128Z"}}
