test:
  image: python:3
  stage: test

  cache:
    paths:
      - "$CI_PROJECT_DIR/pip-cache"
    key: "$CI_PROJECT_ID"

  script:
    - make install-importers
    - make install-lint-dep
    - make lint-test
    - make test
  coverage: '/TOTAL.*\s(\d+)%/'

docs:
  image: thegw/gwio-devenv:latest
  artifacts:
    paths:
      - _build/html

  stage: build
  only:
    refs:
      - master
  script:
    - make docs
