version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop

  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:1.7
    ports:
      - "8080:80"
    restart: always
    hostname: prestashop
    environment:
      DB_USER: prestashop
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_SERVER: db
      PS_DOMAIN: 127.0.0.1:8080
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-dev
      ADMIN_MAIL: admin@admin.com
      ADMIN_PASSWD: admin

volumes:
  db_data:
